
export const languages = [
    "Afrikaans", "Albanian", "Amharic", "Arabic", "Armenian", "Azerbaijani", "Basque", "Belarusian", "Bengali", "Bosnian",
    "Bulgarian", "Catalan", "Cebuano", "Chinese (Simplified)", "Chinese (Traditional)", "Corsican", "Croatian", "Czech",
    "Danish", "Dutch", "English", "Esperanto", "Estonian", "Finnish", "French", "Frisian", "Galician", "Georgian",
    "German", "Greek", "Gujarati", "Haitian Creole", "Hausa", "Hawaiian", "Hebrew", "Hindi", "Hmong", "Hungarian",
    "Icelandic", "Igbo", "Indonesian", "Irish", "Italian", "Japanese", "Javanese", "Kannada", "Kazakh", "Khmer",
    "Kinyarwanda", "Korean", "Kurdish", "Kyrgyz", "Lao", "Latin", "Latvian", "Lithuanian", "Luxembourgish", "Macedonian",
    "Malagasy", "Malay", "Malayalam", "Maltese", "Maori", "Marathi", "Mongolian", "Myanmar (Burmese)", "Nepali",
    "Norwegian", "Nyanja (Chichewa)", "Odia (Oriya)", "Pashto", "Persian", "Polish", "Portuguese", "Punjabi",
    "Romanian", "Russian", "Samoan", "Scots Gaelic", "Serbian", "Sesotho", "Shona", "Sindhi", "Sinhala (Sinhalese)",
    "Slovak", "Slovenian", "Somali", "Spanish", "Sundanese", "Swahili", "Swedish", "Tagalog (Filipino)", "Tajik",
    "Tamil", "Tatar", "Telugu", "Thai", "Turkish", "Turkmen", "Ukrainian", "Urdu", "Uyghur", "Uzbek", "Vietnamese",
    "Welsh", "Xhosa", "Yiddish", "Yoruba", "Zulu"
];

// BCP-47 language codes
export const languageToCode: { [key: string]: string } = {
    "English": "en-US", 
    "Spanish": "es-ES", 
    "French": "fr-FR", 
    "German": "de-DE", 
    "Italian": "it-IT", 
    "Japanese": "ja-JP", 
    "Korean": "ko-KR", 
    "Russian": "ru-RU", 
    "Chinese (Simplified)": "zh-CN",
    "Chinese (Traditional)": "zh-TW",
    "Hindi": "hi-IN",
    "Portuguese": "pt-BR", 
    "Arabic": "ar-SA", 
    "Dutch": "nl-NL", 
    "Polish": "pl-PL", 
    "Indonesian": "id-ID",
    "Turkish": "tr-TR", 
    "Vietnamese": "vi-VN",
    "Afrikaans": "af-ZA",
    "Albanian": "sq-AL",
    "Amharic": "am-ET",
    "Armenian": "hy-AM",
    "Azerbaijani": "az-AZ",
    "Bengali": "bn-BD",
    "Bosnian": "bs-BA",
    "Bulgarian": "bg-BG",
    "Catalan": "ca-ES",
    "Croatian": "hr-HR",
    "Czech": "cs-CZ",
    "Danish": "da-DK",
    "Estonian": "et-EE",
    "Finnish": "fi-FI",
    "Georgian": "ka-GE",
    "Greek": "el-GR",
    "Gujarati": "gu-IN",
    "Hebrew": "he-IL",
    "Hungarian": "hu-HU",
    "Icelandic": "is-IS",
    "Javanese": "jv-ID",
    "Kannada": "kn-IN",
    "Kazakh": "kk-KZ",
    "Khmer": "km-KH",
    "Lao": "lo-LA",
    "Latvian": "lv-LV",
    "Lithuanian": "lt-LT",
    "Macedonian": "mk-MK",
    "Malay": "ms-MY",
    "Malayalam": "ml-IN",
    "Marathi": "mr-IN",
    "Mongolian": "mn-MN",
    "Myanmar (Burmese)": "my-MM",
    "Nepali": "ne-NP",
    "Norwegian": "no-NO",
    "Persian": "fa-IR",
    "Punjabi": "pa-IN",
    "Romanian": "ro-RO",
    "Serbian": "sr-RS",
    "Slovak": "sk-SK",
    "Slovenian": "sl-SI",
    "Somali": "so-SO",
    "Sundanese": "su-ID",
    "Swahili": "sw-TZ",
    "Swedish": "sv-SE",
    "Tagalog (Filipino)": "fil-PH",
    "Tamil": "ta-IN",
    "Telugu": "te-IN",
    "Thai": "th-TH",
    "Ukrainian": "uk-UA",
    "Urdu": "ur-PK",
    "Uzbek": "uz-UZ",
    "Welsh": "cy-GB",
    "Yoruba": "yo-NG",
    "Zulu": "zu-ZA"
};
