
'use server';
import { config } from 'dotenv';
config();

import '@/ai/flows/edit-files-from-prompt.ts';
import '@/ai/flows/generate-image-from-storyboard.ts';
import '@/ai/flows/translate-text-ai.ts';
import '@/ai/flows/chat-research-assistance.ts';
import '@/ai/flows/write-song-and-music.ts';
import '@/ai/flows/create-document-from-prompt.ts';
import '@/ai/flows/text-to-speech.ts';
import '@/ai/flows/generate-video-with-narration.ts';
import '@/ai/flows/import-from-url.ts';
import '@/ai/flows/video-editor.ts';
import '@/ai/flows/generate-chart-from-prompt.ts';
import '@/ai/flows/prompt-enhancer.ts';
import '@/ai/flows/brand-finder.ts';
import '@/ai/flows/shopping-assistant.ts';
import '@/ai/flows/study-material-analyzer.ts';
import '@/ai/flows/find-lyrics-from-url.ts';
import '@/ai/flows/sound-generator.ts';
import '@/ai/flows/supply-chain-ai-planner.ts';
import '@/ai/flows/inventory-auto-forecaster.ts';
import '@/ai/flows/logistics-route-optimizer.ts';
import '@/ai/flows/vendor-risk-scorer.ts';
import '@/ai/flows/fraud-detection-engine.ts';
import '@/ai/flows/transaction-pattern-finder.ts';
import '@/ai/flows/credit-risk-analyzer.ts';
import '@/ai/flows/investment-portfolio-optimizer.ts';
import '@/ai/flows/financial-statement-summarizer.ts';
